version: '3.3'

services:
   codenjoy_db:
     image: postgres:11.1
     container_name: codenjoy-database
     volumes:
       - ./materials/database:/var/lib/postgresql/data
#     ports:                       #P#
#       - "${POSTGRES_PORT}:5432"  #P#
     restart: always
     environment:
         POSTGRES_DB: codenjoy
         POSTGRES_USER: codenjoy
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     networks:
         codenjoy:
             ipv4_address: 172.28.1.4

   nginx:
     image: nginx
     container_name: nginx
     volumes:
       - ./config/nginx/domain.conf:/etc/nginx/domain.conf
       - ./config/nginx/ssl.conf:/etc/nginx/ssl.conf
       - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
       - ./ssl-cert:/usr/share/ca-certificates/extra
     ports: 
#       - "443:443"                                         #S#
       - "80:80"   
     restart: always   
     networks:
         codenjoy:
             ipv4_address: 172.28.1.1
     
networks:
    codenjoy:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
