version: '3.3'

services:
   codenjoy_db:
     image: postgres:11.1
     container_name: codenjoy-database
     volumes:
       - ./materials/database:/var/lib/postgresql/data
     restart: always
     environment:
         POSTGRES_DB: codenjoy
         POSTGRES_USER: codenjoy
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     networks:
         codenjoy:
             ipv4_address: 172.28.1.4

#C# comment this block if you need only balancer
   codenjoy_server:
     depends_on:
       - codenjoy_db
     image: apofig/codenjoy-contest:1.0.28
     container_name: codenjoy-contest
     build:
        context: ./applications
        dockerfile: Dockerfile-contest
     command: java -jar /usr/local/jetty/start.jar -Ddatabase.type=${DATABASE_TYPE}
     volumes: 
#L#       - ./materials/database:/var/lib/jetty/database
       - ./config/codenjoy:/var/lib/jetty/config
       - ./logs/codenjoy/codenjoy-contest.log:/var/lib/jetty/logs/codenjoy-contest.log
     restart: always
     networks:
         codenjoy:
             ipv4_address: 172.28.1.2

   nginx:
     depends_on:
       - codenjoy_server
     image: nginx
     container_name: nginx
     volumes: 
       - ./config/nginx/codenjoy-contest.conf:/etc/nginx/conf.d/codenjoy-contest.conf      #C# 
       - ./config/nginx/domain.conf:/etc/nginx/domain.conf
       - ./config/nginx/ssl.conf:/etc/nginx/ssl.conf
       - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
       - ./ssl-cert:/usr/share/ca-certificates/extra
     ports: 
#S#       - "443:443" 
       - "80:80"   
     restart: always   
     networks:
         codenjoy:
             ipv4_address: 172.28.1.1
     
networks:
    codenjoy:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
