version: '3.3'

services:
   nginx:
     image: nginx
     container_name: nginx
     volumes:
       - ./config/nginx/domain.conf:/etc/nginx/domain.conf
       - ./config/nginx/wordpress.conf:/etc/nginx/conf.d/wordpress.conf
       - ./config/nginx/ssl.conf:/etc/nginx/ssl.conf
       - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
       - ./ssl-cert:/usr/share/ca-certificates/extra
       - /etc/localtime:/etc/localtime:ro
     ports:
       - "80:80"
     restart: always
     networks:
       codenjoy:
         ipv4_address: 172.28.1.1

   wordpress_db:
     image: mysql:5.7
     container_name: wordpress-database
     volumes:
       - ./materials/wordpress/database:/var/lib/mysql
       - /etc/localtime:/etc/localtime:ro
     restart: always
#     ports:
#       - "80:80"
     environment:
         MYSQL_ROOT_PASSWORD: secureWordpressRootDBPassword
         MYSQL_DATABASE: wordpress
         MYSQL_USER: wordpress
         MYSQL_PASSWORD: secureWordpressDBPassword
     networks:
       codenjoy:
         ipv4_address: 172.28.1.7

   wordpress:
     depends_on:
       - wordpress_db
     image: wordpress:latest
     container_name: wordpress
     volumes:
       - ./materials/wordpress/wp_content:/var/www/html/wp-content
       - /etc/localtime:/etc/localtime:ro
     restart: always
     environment:
         WORDPRESS_DB_HOST: wordpress_db:3306
         WORDPRESS_DB_USER: wordpress
         WORDPRESS_DB_PASSWORD: secureWordpressDBPassword
     networks:
       codenjoy:
         ipv4_address: 172.28.1.8

networks:
  codenjoy:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16